# encoding: UTF-8

class String
  TABLE_NORM2RTF = {
    # 'nobrkspace'  => 'a0',
    # 'exclamdown'  => 'a1',
    # 'cent'        => 'a2',
    '£'           => 'a3', # sterling
    # 'currency'    => 'a4',
    # 'yen'         => 'a5',
    # 'brokenbar'   => 'a6',
    # 'section'     => 'a7',
    '¨'           => 'a8', # dieresis
    '©'           => 'a9', # copyright
    # 'ordfeminine' => 'aa',
    # 'guillemotleft' => 'ab',
    # 'logicalnot'  => 'ac',
    # 'opthyphen'   => 'ad',
    # 'registered'  => 'ae',
    # 'macron'      => 'af',
    '°'           => 'b0', # degree
    '±'           => 'b1', # plusminus
    # 'twosuperior' => 'b2',
    # 'threesuperior' => 'b3',
    # 'acute'       => 'b4',
    # 'mu'          => 'b5',
    # 'paragraph'   => 'b6',
    # 'periodcentered'  => 'b7',
    # 'cedilla'     => 'b8',
    # 'onesuperior' => 'b9',
    # 'ordmasculine'=> 'ba',
    # 'guillemotright'  => 'bb',
    '¼'           => 'bc',
    '½'           => 'bd',
    '¾'           => 'be', # ⅓ ⅔
    '¿'           => 'bf',
    # 'Agrave'      => 'c0',
    # 'Aacute'      => 'c1',
    'Â'           => 'c2',
    'Ã'           => 'c3',
    'Ä'           => 'c4',
    # 'Aring'       => 'c5',
    'Æ'           => 'c6',
    'Ç'           => 'c7',
    'È'           => 'c8',
    'É'           => 'c9',
    'Ê'           => 'ca',
    'Ë'           => 'cb',
    # 'Igrave'      => 'cc',
    # 'Iacute'      => 'cd',
    'Î'           => 'ce',
    'Ï'           => 'cf',
    # 'Eth'         => 'd0',
    'Ñ'           => 'd1',
    # 'Ograve'      => 'd2',
    # 'Oacute'      => 'd3',
    'Ô'           => 'd4',
    'Õ'           => 'd5',
    'Ö'           => 'd6',
    # 'multiply'    => 'd7',
    # 'Oslash'      => 'd8',
    'Ù'           => 'd9',
    # 'Uacute'      => 'da',
    'Û'           => 'db',
    'Ü'           => 'dc',
    # 'Yacute'      => 'dd',
    # 'Thorn'       => 'de',
    # 'germandbls'  => 'df',
    'à'           => 'e0',
    # 'aacute'      => 'e1',
    'â'           => 'e2',
    'ã'           => 'e3',
    'ä'           => 'e4',
    # 'aring'       => 'e5',
    'æ'           => 'e6',
    'ç'           => 'e7',
    'è'           => 'e8',
    'é'           => 'e9',
    'ê'           => 'ea',
    'ë'           => 'eb',
    # 'igrave'      => 'ec',
    'ì'           => 'ed',
    'î'           => 'ee',
    'ï'           => 'ef',
    # 'eth'         => 'f0',
    'ñ'           => 'f1',
    # 'ograve'      => 'f2',
    'ò'           => 'f3',
    'ô'           => 'f4',
    'õ'           => 'f5',
    'ö'           => 'f6',
    # 'divide'      => 'f7',
    # 'oslash'      => 'f8',
    # 'ugrave'      => 'f9',
    'ù'           => 'fa',
    'û'           => 'fb',
    'ü'           => 'fc',
    # 'yacute'      => 'fd',
    # 'thorn'       => 'fe',
    'ÿ'           => 'ff',
    '—'           => '97',
    '–'           => '96'
    }

  def to_rtf
    self.gsub(/(#{TABLE_NORM2RTF.keys.join('|')})/){
      "\\'#{TABLE_NORM2RTF[$1]}"
    }.gsub(/\n/, "\\\n")
  end
end #/String
